// Copyright (C) 2026 Leandro Lisboa Penz <lpenz@lpenz.org>
// This file is subject to the terms and conditions defined in
// file 'LICENSE', which is part of this source code package.

//! Complete example: generates a man page for an application with
//! flags, positional arguments, subcommands, value enums and a custom
//! extra section.
//!
//! Run with:
//!
//! ```sh
//! cargo run --example full_manpage
//! ```

use clap::{ArgAction, CommandFactory, Parser, Subcommand, ValueEnum};
use clap2man::Manual;

/// An example application that demonstrates clap2man.
///
/// myapp is an example application used to demonstrate how to generate
/// a complete man page from a clap command definition.
#[derive(Parser)]
#[command(name = "myapp", version = "1.2.3", author = "John Doe <john@doe.com>")]
struct Cli {
    /// Increase verbosity level
    #[arg(short, long, action = ArgAction::Count)]
    verbose: u8,

    /// Read the configuration from FILE
    #[arg(short, long, value_name = "FILE")]
    config: Option<std::path::PathBuf>,

    /// When to colorize the output
    #[arg(short = 'C', long, value_name = "WHEN")]
    color: Option<ColorChoice>,

    /// Input file to process
    input: std::path::PathBuf,

    /// Write the result here instead of stdout
    output: Option<std::path::PathBuf>,

    #[command(subcommand)]
    command: Option<Commands>,
}

#[derive(Subcommand)]
enum Commands {
    /// Validate the input file
    Check {
        /// Stop at the first error found
        #[arg(short, long)]
        strict: bool,
    },
    /// Convert the input file to another format
    Convert {
        /// Write the result to FILE instead of stdout
        #[arg(short, long, value_name = "FILE")]
        output: Option<std::path::PathBuf>,
        /// Target format
        format: Option<Format>,
    },
}

/// Supported output formats
#[derive(Clone, ValueEnum)]
enum Format {
    /// JavaScript Object Notation
    Json,
    /// YAML Ain't Markup Language
    Yaml,
    /// Tom's Obvious, Minimal Language
    Toml,
    /// Comma-Separated Values
    Csv,
}

/// When to colorize the output
#[derive(Clone, ValueEnum)]
enum ColorChoice {
    /// Show colors when the output is a terminal
    Auto,
    /// Always show colors
    Always,
    /// Never show colors
    Never,
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Get the clap::Command generated by the derive macro:
    let cmd = Cli::command();

    let manual = Manual::try_from(&cmd)?;
    let mut manpage: man::Manual = manual.into();

    // The result is a regular man::Manual, so we can further
    // customize it before rendering.
    // Note: the roff crate escapes "-" automatically, so plain
    // dashes are used here:
    manpage =
        manpage.custom(man::Section::new("examples").paragraph(
            "Validate file.txt strictly:\n.TP\nmyapp --config my.conf -s check file.txt",
        ));

    print!("{}", manpage.render());
    Ok(())
}
